import Link from 'next/link'
import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Header from '@/components/header'

const inter = Poppins({ subsets: ['latin'], weight: ['400','500', '600'] })

export const metadata = {
  title: 'Sebastian Barranca',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='mt-28'>
        {children}
        </div>
      </body>
    </html>
  )
}
